---
- name: Helm Install/Upgrade
  hosts: all
  tasks:
  - name: Helm install mpm-frontend-awx
    shell: helm upgrade mpm-frontend-deploy-dev-awx acheron-helm/mpm-frontend-deploy-dev-awx --install --set image_id={{ image_id }} --set build_id={{ build_id }}
