---
- name: Helm Install/Upgrade
  hosts: all
  tasks:
  - name: Helm install mpm-frontend-awx
    shell: echo env_config{{ ":" }} "\"{{ env_config }}\"" > /home/administrator/ansible_playbook_inventory/{{ project_name }}
